<?php
/**
 * Created by PhpStorm.
 * User: muxtor
 * Date: 1/16/18
 * Time: 11:21 AM
 */

namespace muxtor\pkk5component;

use yii\base\Component;

class RemoteLoad extends Component
{
    /**
     * @var string
     */
    public $with = 'withCurl';

    /**
     * Инитилизация
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $link
     * @param null $with
     * @return bool|mixed
     */
    public function load($link,$with=null)
    {
        //Получить тип лоадер
        if($with!=null) $this->with = $with;

        $with = $this->with;
        $load = new RemoteLoad();
        if(property_exists($load, $with)){ //проверка на наличие функцию
            //получить данны по опции
            return $load->$with($link);
        }else{
            //возможно вывести об ощибку или...
            return $load->withCurl($link);
        }
    }

    /**
     * @param $link
     * @return bool|mixed
     */
    public function withCurl($link)
    {
        // Скачиваем файл используя cURL: http://ru2.php.net/manual/ru/book.curl.php
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $link);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);
        $this_header = [
            'Referer: http://google.com/',
        ];

        curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36');
        curl_setopt($ch, CURLOPT_HTTPHEADER, $this_header);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        $data = curl_exec($ch);
        $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        return ($httpcode>=200 && $httpcode<300) ? $data : false;
    }

    /**
     * @param $link
     * @return string
     */
    public function withGetFileContents($link)
    {
        // Скачиваем файл используя file_get_contents: http://ru2.php.net/manual/ru/function.file-get-contents.php
        return file_get_contents($link);//получить данны с ссылку
    }
}